language: node_js
node_js:
  - "14.18.1"

branches:
  only:
    - master

before_script:
  - npm install -g @ionic/cli
  - npm ci

script:
  - npm run build --prod -- --base-href ./

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: dist
