language: node_js
dist: bionic
node_js:
  - "stable"

branches:
  only:
    - master

before_script:
  - npm install -g @ionic/cli
  - npm ci

script:
  - npm run build

before_deploy:
  - npm run test:unit

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: dist
